import { Button, VerticalBox, HorizontalBox, ScrollView, HorizontalBox } from "std-widgets.slint";

export struct SlintCusFile {
    path: string,
    region: string,
    data_size: int,
    invalid: bool}

export global GlobalVariables {
    in-out property<string> app-version: "1.0.2";
    in property <string> local_region: "";
    in-out property <[SlintCusFile]> files_excluding_USA;
    in-out property <[SlintCusFile]> files_excluding_KOR;
    in-out property <[SlintCusFile]> files_excluding_RUS;

    in-out property <string> selected_region: "";
    in-out property <bool> convert_button_flashing: false;
    in-out property <bool> automatically_converting: false;

    callback request-refresh-files();
    callback convert-files();
    callback toggle-automatic-conversion();
    callback selected-region-changed(string);
}

global RegionHelper {
    public pure function get_unconverted_files(excluded_file_region: string) -> [SlintCusFile] {
        if (excluded_file_region == "USA") {
            return GlobalVariables.files_excluding_USA;
        } else if (excluded_file_region == "KOR") {
            return GlobalVariables.files_excluding_KOR;
        } else if (excluded_file_region == "RUS") {
            return GlobalVariables.files_excluding_RUS;
        }
        
        return [];
    }

    public pure function get_unconverted_files_size(file_region: string) -> int {
        if (file_region == "USA") {
            return GlobalVariables.files_excluding_USA.length;
        } else if (file_region == "KOR") {
            return GlobalVariables.files_excluding_KOR.length;
        } else if (file_region == "RUS") {
            return GlobalVariables.files_excluding_RUS.length;
        }
        return 0;
    }

    public pure function is_unconverted_files_empty(excluded_file_region: string) -> bool {
        if (excluded_file_region == "USA") {
            return GlobalVariables.files_excluding_USA.length == 0;
        } else if (excluded_file_region == "KOR") {
            return GlobalVariables.files_excluding_KOR.length == 0;
        } else if (excluded_file_region == "RUS") {
            return GlobalVariables.files_excluding_RUS.length == 0;
        }
        return true;
    }

    public pure function is_file_converted(file_region: string) -> bool {
        if (file_region != GlobalVariables.local_region) {
            return false;
        }
        return true;
    }

    public pure function get-flag-image(region: string) -> image {
        if (region == "USA") {
            return @image-url("assets/USA-flag.svg");
        }
        if (region == "KOR") {
            return @image-url("assets/KOR-flag.svg");
        }
        if (region == "RUS") {
            return @image-url("assets/RUS-flag.svg");
        }
        return @image-url("assets/icon-half.ico");
    }
}

component RegionButton inherits Rectangle {
    in-out property <bool> toggled;

    in property <image> region_flag;
    in property <string> region_name;

    property <int> name;
    property <color> normal-color: #2a2730;
    property <color> hover-color: #4a4458;
    property <color> pressed-color: #1a1620;
    property <color> toggled-color: #6d4c7d;

    property <length> default_padding: 20px;
    property <length> default_font_size: 18px;

    background: area.pressed ? pressed-color : toggled ? toggled-color : area.has-hover ? hover-color : normal-color;

    animate background { duration: 150ms; }

    border-radius: 2px;
    width: 100px;
    height: 36px;

    callback select-region;
    area := TouchArea {
        width: parent.width;
        height: parent.height;
        mouse-cursor: pointer;
        clicked => {
            root.select-region();
            GlobalVariables.request_refresh_files();
        }
    }

    HorizontalBox {
        alignment: center;
        Text {
            horizontal-alignment: center;
            vertical-alignment: center;
            font-size: default_font_size - 2px;
            text: region_name;
        }

        Rectangle {
            Image {
                width: 32px;
                vertical-alignment: center;
                horizontal-alignment: center;
                source: region_flag;
                image-fit: contain;
            }
        }
    }
}

component RegionPanel inherits Rectangle {
    property <[string]> regions: ["USA", "KOR", "RUS"];

    HorizontalBox {
        spacing: 25px;

        for region in regions: RegionButton {
            region_name: region;
            region_flag: RegionHelper.get-flag-image(region);
            toggled: GlobalVariables.selected_region == region;
            select_region => {
                if (GlobalVariables.selected_region != region) {
                    GlobalVariables.selected_region = region;
                    GlobalVariables.selected-region-changed(region);
                }
            }
        }
    }
}

component FileSlot inherits Rectangle {
    in-out property <SlintCusFile> file;
    in-out property <bool> converted: file.region == GlobalVariables.selected_region;
    property <length> default_font_size: 18px;

    border-radius: 8px;
    width: 270px;
    height: 40px;
    background: converted ? #2B3851 : #A8293B;

    VerticalLayout {
        HorizontalBox {
            alignment: space-between;
            Text {
                vertical-alignment: center;
                text: file.path;
            }

            Image {
                width: 24px;
                source: RegionHelper.get-flag-image(file.region);
                image-fit: contain;
            }
        }
    }
}

component FilePanel {
    VerticalLayout {
        Text {
            font-size: 24px;
            vertical-alignment: center;
            horizontal-alignment: center;
            text: @tr("Local Incompatible Files");
        }

        ScrollView {
            // Absolute Width and Height of the actual view
            width: 300px;
            height: 200px;

            // How much we can scroll
            viewport-height: RegionHelper.get_unconverted_files_size(GlobalVariables.selected_region) * 50px;
            viewport-width: 300px;

            VerticalBox {
                for file[index] in RegionHelper.get_unconverted_files(GlobalVariables.selected_region): FileSlot {
                    file: file;
                }
            }
        }
    }
}

component AutomaticConversionButton inherits Rectangle {
    height: 60px;
    width: 160px;
    border-radius: 8px;
    background: GlobalVariables.automatically_converting ? activated-color : area.pressed ? pressed-color : area.has-hover ? hover-color : normal-color;

    property <color> normal-color: #2a2730;
    property <color> hover-color: #4a4458;
    property <color> pressed-color: #1a1620;
    property <color> activated-color: 	#c37b9f;

    property <color> activated-text-color: #FFFFFF00;

    property <length> default_padding: 20px;
    property <length> default_font_size: 18px;

    animate background {
        duration: 150ms;
        easing: ease-out;
    }

    callback automatic-conversion-clicked();

    area := TouchArea {
        // TODO: Maybe a callback to when the thread is actually started or something? What happens when we press this really fast.
            // Either use a bool value from the callback, or have another variable to keep track of for when the thread is actually started.
        enabled: true;
        width: parent.width;
        height: parent.height;
        mouse-cursor: pointer;

        clicked => {
            root.automatic-conversion-clicked();
        }
    }

    Image {
        animate opacity {
            duration: 150ms;
            easing: ease-in-out;
        }
        visible: GlobalVariables.automatically_converting;
        opacity: GlobalVariables.automatically_converting ? 100% : 0%;
        width: 48px;
        height: 48px;
        source: @image-url("assets/icon-full.ico");
        accessible-label: "Automatic Conversion Image";
        image-fit: fill;

        rotation-angle: GlobalVariables.automatically_converting ? sin(360deg * animation-tick() / 3s) * 10deg : 0deg;
        rotation-origin-x: self.width / 2;
        rotation-origin-y: self.height / 2;
    }

    Text {
        visible: GlobalVariables.automatically_converting ? false : true;

        animate color {
            duration: 150ms;
            easing: ease-out;
        }
        animate font-weight {
            duration: 150ms;
            easing: ease-out;
        }
        animate font-size {
            duration: 150ms;
            easing: ease-out;
        }

        color: GlobalVariables.automatically_converting ? activated-text-color : #FFFFFFFF;

        horizontal-alignment: center;
        vertical-alignment: center;
        font-size: 20px;
        text: @tr("🔄 Auto");
    }
}

component ConvertButton inherits Rectangle {
    width: GlobalVariables.automatically_converting ? 0px : 160px;
    height: 60px;
    opacity: GlobalVariables.automatically_converting ? 0% : 100%;
    background: GlobalVariables.convert_button_flashing ? flash-color : area.pressed ? pressed-color : area.has-hover ? hover-color : normal-color;
    border-radius: 8px;

    property <color> normal-color: #2a2730;
    property <color> hover-color: #4a4458;
    property <color> pressed-color: #1a1620;
    property <color> flash-color: #2ecc71;

    property <color> flash-text-color: #1a1620;

    property <length> default_padding: 20px;
    property <length> default_font_size: 18px;

    animate background {
        duration: 150ms;
        easing: ease-out;
    }
    animate width {
        duration: 150ms;
        easing: ease-out;
    }
    animate opacity {
        duration: 150ms;
        easing: ease-out;
    }

    callback convert-clicked();

    // TODO: Minor bug - The pointer doesn't go back from default state to pointer state when clicked and unmoved.
    area := TouchArea {
        enabled: GlobalVariables.automatically_converting ? false : GlobalVariables.convert_button_flashing ? false : true;
        width: parent.width;
        height: parent.height;
        mouse-cursor: pointer;
        clicked => {
            root.convert-clicked();
        }
    }

    Text {
        opacity: GlobalVariables.automatically_converting ? 0% : 100%;
        animate color {
            duration: 150ms;
            easing: ease-out;
        }
        animate font-weight {
            duration: 150ms;
            easing: ease-out;
        }
        animate font-size {
            duration: 150ms;
            easing: ease-out;
        }
        font-weight: GlobalVariables.convert_button_flashing ? 600 : 400;
        color: GlobalVariables.convert_button_flashing ? flash-text-color : #FFFFFFFF;
        horizontal-alignment: center;
        vertical-alignment: center;
        font-size: GlobalVariables.convert_button_flashing ? 24px : 20px;
        text: GlobalVariables.convert_button_flashing ? @tr("🥳 Success!") : @tr("🛠️ Convert");
    }
}

component Background inherits Rectangle {
    Image {
        source: @image-url("assets/background.jpg");
        image-fit: preserve;
        accessible-label: "Background_Image";
    }
}

export component AppWindow inherits Window {
    // TODO Minor bug: White background on first frame, has to do with opengl and skia backend renderer.
    icon: @image-url("assets/icon-half.ico");
    title: @tr("PresetWeaver v.") + GlobalVariables.app-version;
    always-on-top: true;
    background: transparent;
    width: 768px;
    height: 800px;
    default-font-family: "Segoe UI";

    Background { }

    VerticalLayout {
        spacing: 20px;
        alignment: center;
        HorizontalLayout {
            alignment: center;
            Text {
                font-size: 20px;
                font-weight: 600;
                text: @tr("Detected Region: ") + GlobalVariables.local_region;
            }
        }

        HorizontalLayout {
            alignment: center;
        }

        HorizontalLayout {
            alignment: center;
            FilePanel { }
        }

        VerticalBox {
            alignment: center;
            spacing: 8px;

            HorizontalLayout {
                alignment: center;
                RegionPanel { }
            }

            HorizontalLayout {
                alignment: center;

                AutomaticConversionButton {
                    automatic-conversion-clicked => {
                        GlobalVariables.toggle-automatic-conversion();
                    }
                }

                Rectangle {
                    width: 5px;
                }

                ConvertButton {
                    convert_clicked => {
                        GlobalVariables.convert-files();
                    }
                }
            }
        }
    }
}
